name: Test and deploy

on:
- push
- workflow_dispatch

jobs:
  test_and_deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up JavaScript
      uses: actions/setup-node@v1
      with:
        node-version: 6.14.4
    - name: Install JavaScript dependencies and build
      run: |
        npm install
    - name: Run JavaScript tests
      run: npm test

